vim.keymap.set({ "n", "v" }, ";", ":")
vim.keymap.set("i", "jk", "<esc>")
vim.keymap.set("i", "<c-c>", "<Esc>")
vim.keymap.set("n", "<bs>", '<C-^>`"zz')
vim.keymap.set("n", "<leader>=", "<C-w>=")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "J", "mzJ`z")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set("n", "U", "<C-R>")
vim.keymap.set("n", "c*", "*``cgn")
vim.keymap.set("n", "c#", "#``cgN")
vim.keymap.set("n", "Q", "<nop>")
vim.keymap.set({ "n", "v" }, "<leader>p", [["_dP]])
vim.keymap.set({ "n", "v" }, "<leader>d", [["_d]])
vim.keymap.set({ "n", "v" }, "<leader>c", [["_c]])
vim.keymap.set({ "n", "v" }, "<leader>y", [["+y]])
vim.keymap.set({ "n", "v" }, "<leader>Y", [["+Y]])
vim.keymap.set({ "n", "v", "i" }, "<S-down>", "<C-d>zz")
vim.keymap.set({ "n", "v", "i" }, "<S-up>", "<C-u>zz")
vim.keymap.set("ia", "ife", "if err != nil {<CR>log.Fatal(err)<CR>}")
vim.keymap.set("n", "<tab>", "gt")
vim.keymap.set("n", "<s-tab>", "gT")

-- Terminal config
vim.keymap.set("t", "jk", "<C-\\><C-n>")
vim.keymap.set("t", "<esc>", "<C-d><cr>")
vim.keymap.set("t", "<C-j>", "<C-\\><C-n><C-w>j")
vim.keymap.set("t", "<C-k>", "<C-\\><C-n><C-w>k")
vim.keymap.set("t", "<C-h>", "<C-\\><C-n><C-w>h")
vim.keymap.set("t", "<C-l>", "<C-\\><C-n><C-w>l")
vim.keymap.set("n", "so", "<C-w>o")
vim.keymap.set("n", "sh", "<C-w>h")
vim.keymap.set("n", "sk", "<C-w>k")
vim.keymap.set("n", "sj", "<C-w>j")
vim.keymap.set("n", "sl", "<C-w>l")
vim.keymap.set("n", "tt", ":tab term<cr>")
vim.keymap.set("n", "tf", ":term<cr>")
vim.keymap.set("n", "tj", ":vert term<cr>")
vim.keymap.set("n", "st", function()
	vim.cmd.new()
	vim.cmd.wincmd("j")
	vim.api.nvim_win_set_height(0, 15)
	vim.api.nvim_set_option_value("winfixheight", true, { win = 0 })
	vim.cmd("term")
end)
